language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script: composer update

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/php-coveralls/php-coveralls/bin/php-coveralls
